// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:valotips/model/ability/ability.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'agent.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'agent.g.dart';

@freezed
class Agent with _$Agent {
  const factory Agent({
    required String uuid,
    required String displayName,
    required String description,
    required String developerName,
    required String? dispalyIcon,
    required List<Ability> abilities,
  }) = _Agent;

  factory Agent.fromJson(Map<String, Object?> json) => _$AgentFromJson(json);
}
