// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'stage.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'stage.g.dart';

@freezed
class Stage with _$Stage {
  const factory Stage({
    required String uuid,
    required String displayName,
    required String listViewIcon,
  }) = _Stage;

  factory Stage.fromJson(Map<String, Object?> json) => _$StageFromJson(json);
}
