// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'ability.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'ability.g.dart';

@freezed
class Ability with _$Ability {
  const factory Ability({
    required String slot,
    required String displayName,
    required String description,
    required String? displayIcon,
  }) = _Ability;

  factory Ability.fromJson(Map<String, Object?> json) =>
      _$AbilityFromJson(json);
}
